# Generated by Django 4.2.1 on 2023-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='año_datos',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_empleados',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='', max_length=20),
        ),
    ]
