# Generated by Django 4.2.1 on 2023-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_año_datos_cliente_numero_empleados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor_emision_consumo_energiaelectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAIS', models.CharField(default='', max_length=20)),
                ('FACTOR_EMISION_ELECTRICIDAD', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Factor_emision_gas_refrigerante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO_REFRIGERANTE', models.CharField(max_length=20)),
                ('GWP', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
