# Generated by Django 4.2.1 on 2023-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_factor_emision_consumo_energiaelectrica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor_emision_consumo_energiaelectrica',
            name='AÑO_FACTOR_EMISION',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
