# Generated by Django 4.2.1 on 2023-06-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_factor_emision_consumo_energiaelectrica_año_factor_emision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor_emision_consumo_energiaelectrica',
            options={'ordering': ['AÑO_FACTOR_EMISION'], 'verbose_name': 'Factor de emisión por consumo de energía (kg CO2e/kWh)', 'verbose_name_plural': 'Factores de emisión por consumo de energía (kg CO2e/kWh)'},
        ),
        migrations.AlterModelOptions(
            name='factor_emision_gas_refrigerante',
            options={'verbose_name': 'Tipo de Refrigerante (AR5)', 'verbose_name_plural': 'Tipos de Refrigerantes (AR5)'},
        ),
        migrations.RenameField(
            model_name='alcance1',
            old_name='cantidad_refrigerante',
            new_name='cantidad_refrigerante_kg',
        ),
    ]
