# Generated by Django 4.2.1 on 2023-06-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_factor_emision_consumo_energiaelectrica_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcance2',
            old_name='consumo_energia_electrica',
            new_name='consumo_energia_electrica_kwh',
        ),
    ]
